# Generated by Django 5.2.6 on 2025-09-11 05:33

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('company_name', models.CharField(blank=True, choices=[('ANDO', 'ANDO'), ('KAM', 'KAM'), ('MATE', 'MATE')], max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.CharField(blank=True, choices=[('Head of Sales', 'Head of Sales'), ('Facilitator', 'Facilitator'), ('Product Brand Manager', 'Product Brand Manager'), ('Corporate Manager', 'Corporate Manager'), ('Corporate Officer', 'Corporate Officer'), ('Zonal Sales Executive', 'Zonal Sales Executive'), ('Mobile Sales Officer', 'Mobile Sales Officer'), ('Desk Sales Officer', 'Desk Sales Officer'), ('Admin', 'Admin')], max_length=100, null=True)),
                ('zone', models.CharField(blank=True, choices=[('Coast Zone', 'Coast Zone'), ('Corporate', 'Corporate'), ('Central Zone', 'Central Zone'), ('Southern Zone', 'Southern Zone'), ('Northern Zone', 'Northern Zone'), ('Lake Zone', 'Lake Zone')], max_length=100, null=True)),
                ('branch', models.CharField(blank=True, choices=[('Chanika', 'Chanika'), ('Mikocheni', 'Mikocheni'), ('Morogoro', 'Morogoro'), ('Zanzibar', 'Zanzibar'), ('ANDO HQ', 'ANDO HQ'), ('Dodoma', 'Dodoma'), ('Singida', 'Singida'), ('Tabora', 'Tabora'), ('Mbeya', 'Mbeya'), ('Tunduma', 'Tunduma'), ('Arusha', 'Arusha'), ('Moshi', 'Moshi'), ('Mwanza', 'Mwanza'), ('Geita', 'Geita')], max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Tanzanian phone number (e.g. +255712345678 or 0712345678)', regex='^(?:\\+255|0)[67][0-9]\\d{7}$')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
