# Generated by Django 5.2.6 on 2025-09-11 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meeting_stage', models.CharField(choices=[('Prospecting', 'Prospecting'), ('Qualifying', 'Qualifying'), ('Proposal or Negotiation', 'Proposal or Negotiation'), ('Payment Followup', 'Payment Followup')], default='Prospecting', max_length=50)),
                ('item_discussed', models.TextField(max_length=255)),
                ('client_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Won', 'Won'), ('Closed', 'Closed'), ('Lost', 'Lost')], default='Open', max_length=20, null=True)),
                ('tag', models.CharField(blank=True, choices=[('Prospector', 'Prospector'), ('Lead', 'Lead'), ('Customer', 'Customer')], default='Prospector', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='customer.customer')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='customer.customercontact')),
            ],
        ),
        migrations.CreateModel(
            name='VisitProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productionline', models.CharField(choices=[('RESIN_ROOFING_SHEETS', 'RESIN ROOFING SHEETS'), ('ROOF_PAINT', 'ROOF PAINT'), ('UPVC', 'UPVC'), ('WALL_COATING', 'WALL COATING'), ('ZEBRA_TILES', 'ZEBRA TILES')], max_length=30)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_lines', to='visits.newvisit')),
            ],
        ),
    ]
