# Generated by Django 5.2.6 on 2025-09-13 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_newvisit_visitproductionline'),
    ]

    operations = [
        migrations.AddField(
            model_name='newvisit',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='newvisit',
            name='contract_outcome',
            field=models.CharField(blank=True, choices=[('Won', 'Won'), ('Lost', 'Lost')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='newvisit',
            name='is_order_final',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newvisit',
            name='payment_collected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newvisit',
            name='reason_lost',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newvisit',
            name='meeting_stage',
            field=models.CharField(choices=[('Prospecting', 'Prospecting'), ('Qualifying', 'Qualifying'), ('Proposal or Negotiation', 'Proposal or Negotiation'), ('Closing', 'Closing')], default='Prospecting', max_length=50),
        ),
        migrations.AlterField(
            model_name='newvisit',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Won Paid', 'Won Paid'), ('Won Pending Payment', 'Won Pending Payment'), ('Lost', 'Lost')], default='Open', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newvisit',
            name='tag',
            field=models.CharField(blank=True, choices=[('Prospect', 'Prospect'), ('Lead', 'Lead'), ('Customer', 'Customer')], default='Prospect', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProductInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_interested', models.CharField(choices=[('RESIN_ROOFING_SHEETS', 'RESIN ROOFING SHEETS'), ('ROOF_PAINT', 'ROOF PAINT'), ('UPVC', 'UPVC'), ('WALL_COATING', 'WALL COATING'), ('ZEBRA_TILES', 'ZEBRA TILES')], max_length=30)),
                ('order_estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('final_order_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_collected', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='visits.newvisit')),
            ],
        ),
        migrations.DeleteModel(
            name='VisitProductionLine',
        ),
    ]
